version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/twitter-clone
permissions:
  - object: /var/www/twitter-clone
    pattern: "**"
    owner: nginx
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 180
      runas: root
